version: '3'
services:
  postgres:
    image: postgres:9.4-alpine
    volumes:
        - ./db.sh:/docker-entrypoint-initdb.d/db.sh
    restart: always
    environment:
       POSTGRES_PASSWORD:
       POSTGRES_USER: postgres
       POSTGRES_DB: api
    expose:
       - 5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 15s
        timeout: 10s
        retries: 5
  web:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "43037:43037"
    volumes:
       - .:/usr/src/app
    depends_on:
      - postgres
    command: ["npm", "run", "setup"]